@url=http://localhost:3000/api/

### 
get {{url}}user?username=tomic&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWljIiwic3ViIjoyLCJpYXQiOjE3MDA4MzcyMzIsImV4cCI6MTcwMDkyMzYzMn0.d4QG7eJGXXp3QLoB5Mw-y1zv_Ws4g_e5J1XfEKEf130

###
post {{url}}user

### 
get {{url}}logs

### 
get {{url}}logs/group


### 
get {{url}}logs/query

###
get {{url}}logs/notExistMethod


###
post {{url}}user/test/11/awesome?a=vvv&b=2
Content-Type: application/json

{
    "username": "xxx",
    "password": "ccc"
}

###
post {{url}}auth/signin
Content-Type: application/json

{
    "username": "tomic",
    "password": "123456"
}

###
get {{url}}user/profile?id=11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWljIiwic3ViIjoyLCJpYXQiOjE3MDA0MDI1NDIsImV4cCI6MTcwMDQ4ODk0Mn0.aQfP_ofmLVbivxlxsfe1OiMG_DDZD5lcUvZkSHv_oYg

###
post {{url}}auth/signup
Content-Type: application/json

{
    "username": "tomic",
    "password": "123456"
}
